// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iASMgr_okbhrPM5BBTejG8cb93aKNCI',
    appId: '1:939168380526:web:e81e8226c2a567cab6d87f',
    messagingSenderId: '939168380526',
    projectId: 'flutterfirenote-2f381',
    authDomain: 'flutterfirenote-2f381.firebaseapp.com',
    storageBucket: 'flutterfirenote-2f381.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_LsNo6XfplCL4NJO1VO5F7d5NNCei9Y',
    appId: '1:939168380526:android:d1085a22b8448697b6d87f',
    messagingSenderId: '939168380526',
    projectId: 'flutterfirenote-2f381',
    storageBucket: 'flutterfirenote-2f381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jggjrSjh-YvLfg9wcjy1RmIkmQeRSBU',
    appId: '1:939168380526:ios:66a38f785a7fa955b6d87f',
    messagingSenderId: '939168380526',
    projectId: 'flutterfirenote-2f381',
    storageBucket: 'flutterfirenote-2f381.appspot.com',
    iosBundleId: 'com.example.chatappWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jggjrSjh-YvLfg9wcjy1RmIkmQeRSBU',
    appId: '1:939168380526:ios:66a38f785a7fa955b6d87f',
    messagingSenderId: '939168380526',
    projectId: 'flutterfirenote-2f381',
    storageBucket: 'flutterfirenote-2f381.appspot.com',
    iosBundleId: 'com.example.chatappWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4iASMgr_okbhrPM5BBTejG8cb93aKNCI',
    appId: '1:939168380526:web:92199d7cdb18c4e1b6d87f',
    messagingSenderId: '939168380526',
    projectId: 'flutterfirenote-2f381',
    authDomain: 'flutterfirenote-2f381.firebaseapp.com',
    storageBucket: 'flutterfirenote-2f381.appspot.com',
  );

}